apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: mathtrail-identity

build:
  local:
    push: false
    tryImportMissing: false
  insecureRegistries:
    - ${REGISTRY}
  artifacts:
    - image: identity-ui
      custom:
        buildCommand: buildah bud --tag $IMAGE . && buildah push --tls-verify=false $IMAGE
        dependencies:
          paths:
            - identity-ui/
            - Dockerfile

manifests:
  rawYaml:
    - dapr/components.yaml
    - manifests/network-policies.yaml

deploy:
  kubectl:
    defaultNamespace: ${NAMESPACE}
  helm:
    releases:
      # --- Ory Infrastructure (vendored in mathtrail-charts) ---
      - name: kratos
        repo: ${CHARTS_REPO}
        remoteChart: kratos
        namespace: ${NAMESPACE}
        createNamespace: true
        valuesFiles:
          - values/kratos-values.yaml
        wait: true

      - name: hydra
        repo: ${CHARTS_REPO}
        remoteChart: hydra
        namespace: ${NAMESPACE}
        valuesFiles:
          - values/hydra-values.yaml
        wait: true

      - name: keto
        repo: ${CHARTS_REPO}
        remoteChart: keto
        namespace: ${NAMESPACE}
        valuesFiles:
          - values/keto-values.yaml
        wait: true

      - name: oathkeeper
        repo: ${CHARTS_REPO}
        remoteChart: oathkeeper
        namespace: ${NAMESPACE}
        valuesFiles:
          - values/oathkeeper-values.yaml
        wait: true

      # --- Identity UI (custom service, library chart) ---
      - name: identity-ui
        chartPath: infra/helm/identity-ui
        namespace: ${NAMESPACE}
        wait: true
        valuesFiles:
          - infra/helm/identity-ui/values.yaml
          - infra/helm/values-dev.yaml
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_identity_ui}}"
          image.tag: "{{.IMAGE_TAG_identity_ui}}"

portForward:
  - resourceType: service
    resourceName: kratos-public
    namespace: ${NAMESPACE}
    port: 4433
    localPort: 4433
  - resourceType: service
    resourceName: kratos-admin
    namespace: ${NAMESPACE}
    port: 4434
    localPort: 4434
  - resourceType: service
    resourceName: hydra-public
    namespace: ${NAMESPACE}
    port: 4444
    localPort: 4444
  - resourceType: service
    resourceName: hydra-admin
    namespace: ${NAMESPACE}
    port: 4445
    localPort: 4445
  - resourceType: service
    resourceName: keto-read
    namespace: ${NAMESPACE}
    port: 4466
    localPort: 4466
  - resourceType: service
    resourceName: keto-write
    namespace: ${NAMESPACE}
    port: 4467
    localPort: 4467
  - resourceType: service
    resourceName: oathkeeper-proxy
    namespace: ${NAMESPACE}
    port: 4455
    localPort: 4455
  - resourceType: service
    resourceName: oathkeeper-api
    namespace: ${NAMESPACE}
    port: 4456
    localPort: 4456
  - resourceType: service
    resourceName: identity-ui
    namespace: ${NAMESPACE}
    port: 8080
    localPort: 8090
